apiVersion: v1
kind: Config
preferences: {}
clusters:
- name: mykube
  cluster:
    certificate-authority-data: ca.crt
    server: https://192.168.99.107:8443
contexts:
- name: lainoadmin-mykube
  context:
    cluster: mykube
    user: lainoadmin
current-context: lainoadmin-mykube
users:
- name: lainoadmin
  user:
    client-certificate-data: client.crt
    client-key-data: client.key
