
apiVersion: v1
kind: Config
clusters:
- name: mykube
  cluster:
    certificate-authority: ca.crt
    server: https://192.168.99.107:8443
contexts:
- name: lainoadmin-mykube
  context:
    cluster: mykube
    namespace: default
    user: lainoadmin
current-context: lainoadmin-mykube
users:
- name: lainoadmin
  user:
    token: ${token}