apiVersion: v1
kind: PersistentVolume
metadata:
  name: lainotik-pv-{vol}
  labels:
    type: local
spec:
  storageClassName: {clasname}
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/{vol}"