apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lainotik-{user}-clusterRole
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "events", "persistentvolumeclaims"]
  verbs: ["get", "watch", "list", "create", "delete"]